# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3af92da30b97a046db2671fdc06d4587"
name = "discount filters"
application_url = "https://powerful-welding-retro-fifty.trycloudflare.com"
embedded = true
handle = "discount-filters"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,read_product_listings,read_metaobjects,write_metaobjects, read_products, write_products"

[auth]
redirect_urls = ["https://powerful-welding-retro-fifty.trycloudflare.com/auth/callback", "https://powerful-welding-retro-fifty.trycloudflare.com/auth/shopify/callback", "https://powerful-welding-retro-fifty.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
